### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by AdamYLiang** [edherm/SpringBoard#2]
**Todo Lists**
- [x] `todo_lists` should have reference to the project it is related to instead of `author_id` 
- [x] `todo` should belong to a Todo List instead of an `author_id` 

**Message Board**
- [x] Should belong to a project instead of `author_id` 

**Schedule**
- [x] Should belong to a project instead of `author_id`

- [x] Besides comments, I would mark `Polymorphic Associations` as a bonus.

Let me know if you have any questions!

**Comment by edherm** [comment]
Hello, Adam! Thanks for these. I've made the adjustments and am going to be changing the other wiki pages to reflect those changes.
